config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('audios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modules/audios/urls.py
from django.urls import path
from . import views


app_name = 'audios'
urlpatterns = [
    path('', views.index, name='Index'),
]

modules/audios/models.py
from django.db import models
from cloudinary_storage.storage import MediaCloudinaryStorage


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class RecommendedArtist(models.Model):
    band = models.ForeignKey("Artist", on_delete=models.CASCADE)

    def __str__(self):
        return self.band.name


class Artist(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Audio(models.Model):
    name = models.CharField(max_length=255)
    artist = models.ForeignKey(Artist, null=True, on_delete=models.PROTECT)
    genre = models.ForeignKey(Genre, null=True, on_delete=models.PROTECT)
    duration = models.CharField(max_length=10)
    image = models.ImageField(upload_to="songs_image", blank=True, storage=MediaCloudinaryStorage)
    image_link = models.CharField(max_length=255, default="", blank=True)
    file = models.FileField(upload_to="music1")
    category = models.ForeignKey(Category, on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.name} - {self.artist}"


class Playlist(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    image = models.ImageField(upload_to="songs_image", blank=True, storage=MediaCloudinaryStorage)
    songs = models.ManyToManyField(Audio)

    def __str__(self):
        return self.name

modules/audios/views.py
from django.shortcuts import render
from .models import Playlist, Audio


def index(request):
    audios = Audio.objects.select_related('category').all()[:7]
    new_audios = Audio.objects.order_by("-id")[:8]
    playlists = Playlist.objects.all()

    return render(request, 'audios/index.html', {'audios': audios, 'playlists': playlists,
                                                 "new_audios": new_audios})

templates/audios/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{% static 'img/icon/love-song.png' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />

    <script src="{% static 'scripts/page-behavior.js' %}" defer></script>
    <script src="{% static 'scripts/app.js' %}" defer></script>
    <script src="{% static 'scripts/media-player.js' %}" defer></script>
    <script src="{% static 'scripts/responsive.js' %}" defer></script>

    <title>Spotimine</title>
  </head>
  <body>
    <!-- Create ´playList Objets -->
    <script type="text/javascript">
      const myPlayLists = []
      const songsList = []
      let myList = {}
      {% for playlist in playlists %}

            myList = {
          name: "{{ playlist.name }}",
          songs:[
              {% for song in playlist.songs.all %}
                  {% if not forloop.first %},{% endif %}
                  {
                      title: "{{ song.name }}",
                      author: "{{ song.artist }}",
                      file: "{{ song.file.url }}",
                      img: "{% if song.image %} {{ song.image.url }} {% else %} {{ song.image_link }} {% endif %}"
                  }
              {% endfor %}
          ]
          }
          myPlayLists.push(myList)
          myList = {}
      {% endfor %}
    </script>
    <header id="main-header"></header>

    <main class="main">
      <div id="overlay"></div>

      <!--Sidebar section-->

      <aside>
        <div id="navMenu">
          <span></span>
          <span></span>
          <span></span>
        </div>
        <nav class="sidenav">
          <div class="nav-item">
            <a href="{% url 'audios:Index' %}"
              ><i class="fa-sharp fa-solid fa-house"></i> Inicio
            </a>
          </div>
          <!-- <div class="nav-item">
            <a href="#"><i class="fa-solid fa-table-list"></i> Biblioteca </a>
          </div> -->
          <div class="line"></div>
          <div class="songs-container"></div>
        </nav>
      </aside>

      <div class="container">
        {% block content %}
        <!-- content -->
        {% endblock %}
        <div class="media-space"></div>
      </div>
    </main>

    <!-- Media Player -->

    <div class="title-author">
      <h4 class="song-title-author"></h4>
    </div>
    <div class="media-player">
      <div class="son-info">
        <div class="lef">
          <img class="playing-song-img" src="" alt="song-img" />
        </div>
        <div class="right">
          <h4 class="song-title"></h4>
          <span class="song-author"></span>
        </div>
      </div>
      <div class="music-player-container">
        <div class="main-song-controls">
          <img
            src="{% static 'img/mediaPlayer/previous.svg' %}"
            alt=""
            class="icon previous"
            id="previousSong"
          />
          <!--
            <img
              src="{% static 'img/mediaPlayer/Backward.svg' %}"
              alt=""
              class="icon"
              id="Back10"
            />
            -->
          <img
            src="{% static 'img/mediaPlayer/Play.svg' %}"
            alt=""
            class="icon"
            id="PlayPause"
          />
          <!--
            <img
              src="{% static 'img/mediaPlayer/Forward.svg' %}"
              alt=""
              class="icon"
              id="Plus10"
            />
            -->
          <img
            src="{% static 'img/mediaPlayer/next.svg' %}"
            alt=""
            class="icon next"
            id="nextSong"
          />
        </div>
        <div class="controls-music-container">
          <div class="progress-bar">
            <span class="progress"></span>
          </div>
        </div>
        <div class="time-container">
          <span class="time-left" id="CurrentSongTime"></span>
          <span class="divisor"> / </span>
          <span class="time-lef" id="SongLength"></span>
        </div>
        <audio controls preload="metadata" src=""></audio>
      </div>
      <div class="volume-controls vol-disable">
        <img
          src="{% static 'img/mediaPlayer/volume.svg' %}"
          alt=""
          class="icon"
          id="vol"
        />
        <input type="range" step="any" id="volume-slider" class="slider" />
      </div>
    </div>
  </body>
</html>

templates/audios/index.html
{% extends 'audios/base.html' %} {% load static %} {% block content %}

<!-- Playlists -->
<h2 class="title">Listas de Reproducción</h2>
<div class="mar15 playlists">
  {% if playlists %} {% for playlist in playlists %}
  <div class="content mar08 playlist-object">
    <div class="card">
      <img src="{{ playlist.image.url }}" alt="" />
      <h4>{{ playlist.name }}</h4>
    </div>
  </div>
  {% endfor %} {% endif %}
</div>

<!-- Songs -->
<h2 class="title">Canciones</h2>
<div class="songs">
  {% for audio in audios %} {% if audio.category.name == "song" %}
  <div class="song mar08 see-count">
    <div class="content">
      <div class="card get-music" title="{{ audio.name }}">
        <img
          class="add-song hidden"
          src="{% static 'img/mediaPlayer/plus-circle.svg' %}"
          alt=""
        />
        <img
          class="song-img"
          src="
        {% if audio.image %}
          {{ audio.image.url }}
        {% else %}
          {{ audio.image_link }}
        {% endif %}
        "
          alt=""
        />
        <h4>{{ audio.name }}</h4>
        <p>{{ audio.artist }}</p>
        <a href="{{ audio.file.url }}"></a>
      </div>
    </div>
  </div>

  {% endif %} {% endfor %}

  <div class="song mar08">
    <div class="see-more">
      <a class="see-more-link hidden" href="{{ audio.file.url }}">
        MOSTRA TODO</a
      >
    </div>
  </div>
</div>

<h2 class="title">Agregado Recientemente</h2>
<div class="songs">
  {% for audio in new_audios %} {% if audio.category.name == "song" %}
  <div class="song mar08">
    <div class="content">
      <div class="card get-music" title="{{ audio.name }}">
        <img
          class="add-song hidden"
          src="{% static 'img/mediaPlayer/plus-circle.svg' %}"
          alt=""
        />
        <img
          class="song-img"
          src="
        {% if audio.image %}
          {{ audio.image.url }}
        {% else %}
          {{ audio.image_link }}
        {% endif %}
        "
          alt=""
        />
        <h4>{{ audio.name }}</h4>
        <p>{{ audio.artist }}</p>
        <a href="{{ audio.file.url }}"></a>
      </div>
    </div>
  </div>

  {% endif %} {% endfor %}
</div>
{% endblock %}